on:
  push:
    branches:
      - main

    paths:
      - CHANGELOG.md
  workflow_dispatch:

jobs:
  get_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get version from package.json
        id: semver
        uses: martinbeentjes/npm-get-version-action@main
    outputs:
      version: ${{ steps.semver.outputs.current-version }}

  build_and_publish:
    permissions:
      id-token: write
      contents: read
    needs: get_version
    env:
      APP_NAME: ds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: configure-node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          scope: 'telicent-oss'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
      - name: Get node version
        id: node
        run: |
          echo "version=$(node -v)" >> $GITHUB_OUTPUT

      - name: Get node_modules cache
        uses: actions/cache@v4
        id: node_modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ steps.node.outputs.version }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: npm publish --access public --provenance

