name: Publish release candidate
on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          scope: 'telicent-oss'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
      # Install dependencies using pnpm
      - name: Install dependencies
        run: pnpm install

      # Ensure Nx is available
      - name: Install Nx CLI globally
        run: pnpm add -g nx
      - uses: nrwl/nx-set-shas@v4
      - name: Build and publish packages
      # switch from projects to --all when ready
        run: |
          npx nx run-many --target=build --projects=@telicent-oss/rdfservice,@telicent-oss/ontologyservice
          npx nx run-many --target=publish --projects=@telicent-oss/rdfservice,@telicent-oss/ontologyservice
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
