name: CI
on:
  push:
    branches:
      # Change this if your primary branch is not main
      - main
      - release

    workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - uses: nrwl/nx-set-shas@v3
      # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track main origin/main

      - run: npx nx format:check
      - run: npx nx affected -t test,build --parallel=2
      - name: configure-node
        uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: "@Telicent-io"
          always-auth: true
      - name: create .yarnrc file
        run: |
          npm config set "@telicent-io:registry" "https://npm.pkg.github.com/"
          npm config set "//npm.pkg.github.com/:_authToken" ${{ secrets.PACKAGE_PAT }} 
      - name: Install dependencies
        run: |
          yarn publish ./packages/RdfService/dist 
          yarn publish ./packages/OntologyService/dist
        env:
          NPM_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

