name: publish-prerelease.yml
on:
  workflow_dispatch: # Only manual
permissions:
  actions: read
  contents: read
  id-token: write # needed for provenance data generation

jobs:
  publish-prerelease:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - run: git config --global user.name "${{ github.actor }}"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/cache@v4
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - uses: actions/setup-node@v6
        with:
          node-version: 20.19
          registry-url: 'https://registry.npmjs.org/'
          scope: 'telicent-oss'
          token: ${{ secrets.NPM_REGISTRY_TOKEN }}
      - run: LOCAL_MACHINE=false yarn install --frozen-lockfile
      - run: yarn publish:prerelease:ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
