name: Test release candidate
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "main"

jobs:
  test-libraries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20.14
          registry-url: 'https://registry.npmjs.org'
          scope: "telicent-oss"
          token: ${{ secrets.NPM_REGISTRY_TOKEN }}
      # TODO add node_modules cache
      - run: yarn install --frozen-lockfile
      - run: yarn global add nx
      # TODO test nx affected in ci
      # - uses: nrwl/nx-set-shas@v4
      # - uses: npx nx affected:test --base=$NX_BASE --head=$NX_HEAD
      - run: yarn test