name: Test release candidate
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "main"

jobs:
  test-libraries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'
          scope: 'telicent-oss'
          token: ${{ secrets.NPM_REGISTRY_TOKEN }}
      - run: yarn install --frozen-lockfile
      - run: ls ./packages/ontology-icon-react-lib/node_modules/@telicent-oss
      - run: yarn test --exclude="@telicent-oss/catalogservice" --skip-nx-cache # TODO TELFE-873