name: Update docs
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ./packages

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - run: pnpm install
      - run: yarn generate-docs

      - uses: actions/upload-artifact@v2
        with:
          name: RdfService docs
          path: packages/RdfService/dist/docs/

      - uses: actions/upload-artifact@v2
        with:
          name: OntologyService docs
          path: packages/OntologyService/dist/docs/
